package ws02

val tsk = City("Томск")
val nsk = City("Новосибирск")
val spb = City("Санкт-Петербург")
val msk = City("Москва")

val milk = Product("Молоко", 90.0)
val tea = Product("Чай", 250.0)
val coffee = Product("Кофе", 900.0)
val chips = Product("Чипсы", 135.0)
val bread = Product("Хлеб", 60.0)
val water = Product("Вода", 45.0)
val honey = Product("Мёд", 800.0)

val emptyOrder = Order(emptyList(), false)
val customer1Order1 = Order(listOf(milk, coffee, water), true)
val customer1Order2 = Order(listOf(tea, honey, chips), true)
val customer2Order1 = Order(listOf(milk, bread, tea, chips, water), false)
val customer2Order2 = Order(listOf(tea, bread, chips), true)
val customer2Order3 = Order(listOf(milk, coffee, honey), false)
val customer3Order1 = Order(listOf(coffee, coffee, honey, chips), true)
val customer4Order1 = Order(listOf(milk, milk, tea, coffee, chips), false)
val customer4Order2 = Order(listOf(honey, bread, milk, milk), false)
val customer4Order3 = Order(listOf(tea, water, chips), false)
val customer4Order4 = Order(listOf(tea, honey, bread, coffee), false)
val customer5Order1 = Order(listOf(tea, coffee, water), false)
val customer6Order1 = Order(listOf(tea, water, chips), true)

val customer1 = Customer("Дмитрий", tsk, listOf(customer1Order1, customer1Order2))
val customer2 = Customer("Вячеслав", tsk, listOf(customer2Order1, customer2Order2, customer2Order3))
val customer3 = Customer("Михаил", spb, listOf(customer3Order1))
val customer4 = Customer("Руслан", msk, listOf(customer4Order1, customer4Order2, customer4Order3, customer4Order4))
val customer5 = Customer("Николай", nsk, listOf(customer5Order1))
val customer6 = Customer("Андрей", spb, listOf(customer6Order1))

val shop = Shop("Продуктовый 12 21", listOf(customer1, customer2, customer3, customer4, customer5, customer6))
val shopWithoutCustomersFromNsk = Shop("Магазин без покупателей", listOf(customer1, customer2, customer4))
val shopWithoutCustomers = Shop("Магазин без покупателей", emptyList())
val shopWithCustomersWithoutDeliveredOrders = Shop("Продуктовый 12 21", listOf(customer4, customer5))
val shopWithTwoTheMostPopularProducts = Shop("Продуктовый 21 12", listOf(customer4, customer5))